### ISSUE TITLE
Theme styles not carrying over to supported plugins

### ISSUE THREAD

**Issue by joshistoast** [dizzyup/hyper-hypest#17]
After installing some plugins the theme says it has custom styles for, they don't seem to be applying. Mainly the styling for `hyper-search` and `hyper-statusline`.

I turned on dark mode as well.

Expected:
![Expected Result](https://github.com/dizzyup/hyper-hypest/blob/master/assets/preview-with-plugins.jpg?raw=true)

What I got:
![What I Got](https://i.imgur.com/IduawFM.png)

**Comment by dizzyup** [comment]
Hi @joshwcorbett - I'm not using Hyper these days but I shall have a dig this weekend and see if I can get things working again! It's likely some classes changed in the plugins somewhere.

**Comment by dizzyup** [comment]
@joshwcorbett Unfortunately things don't look good for getting any of this working from my side 😞

I installed Hyper today and installed both `hyper-search` and `hyper-statusline`.

As best I can tell `hyper-statusline` seems to have changed the way it styles it's components, and for whatever reason none of the styles in `hypest` take effect - even though all the classnames and markup in both plugins has remained the same. Nothing I add in the styles has any effect, regardless of specificity.

The un-styled search UI you're seeing is actually Hyper's built in search (which unfortunately it's still impossible to theme because they have inline styles on the container - https://github.com/vercel/hyper/issues/5890). There's an issue with `hyper-search` in Hyper itself -  if you go to the `Edit` menu and go into the `Find` submenu (which is the menu that `hyper-search` adds), all of the options in there will throw an error in a macOS alert dialog window. 
<img width="372" alt="CleanShot 2021-09-25 at 12 21 30@2x" src="https://user-images.githubusercontent.com/717867/134769751-61b842d4-a16c-4396-89cd-4751f97b8e5c.png">

**Comment by joshistoast** [comment]
I feel like the screenshots in the readme should be replaced if they're not achievable

**Comment by dizzyup** [comment]
Yeah, think that's fair enough! Have removed the references from the readme and will do the same for the website when I have some time.
