### ISSUE TITLE
Is there a way to adjust the vibrancy level?

### ISSUE THREAD

**Issue by realvect0r** [dizzyup/hyper-hypest#9]
As the title

**Comment by dizzyup** [comment]
@realVEct0r To enable/disable entirely? Or to have granular control over the amount of vibrancy?

There's a PR submitted that would address adjusting the amount, but I need to find a weekend to bring the changes in so that the preferences work with everything else and the defaults remain as they are today - https://github.com/dizzyup/hyper-hypest/pull/8
